blank_issues_enabled: false
contact_links:
  - name: 📖 Documentación del proyecto
    url: https://github.com/pablorincones95/aethel-software/blob/main/README.md
    about: Lee el README antes de abrir un issue
